<?php

define("HEADER_TITLE", "Computer-Forensik-System Coex");
define("MENU_CAPABILITIES", "Capabilities");
define("MENU_INSTALL", "Installieren");
define("MENU_ARCHITECTURE", "Architektur");
define("MENU_ABOUT", "Informationen über uns");
define("ARCHITECTURE_OF_SYSTEM", "Systemarchitektur");
define("NEWS_OF_PROJECT", "Nachrichten von Projekt");
define("CAPABILITIES_INFO", "Unsere Software-System sammelt Informationen aus einer Vielzahl von Quellen auf dem Zielrechner.");
define("COEX_WHAT", "Was ist die COEX-Software?");
define("COEX_DESCRIPTION", "Die Software für Computer-Forensik im Rahmen von Gerichtsverfahren , und entwickelt, um die Sammlung von Informationen über den Verdächtigen Computer zu erleichtern.");
define("DOWNLOAD_AND_RUN", "Herunterladen und ausführen.");
define("CLONE_AND_BUILD", "Clone-Repository und kompilieren.");
define("COEX_CHROME_MODULE", "Chrome-Modul");
define("COEX_CHROME_MODULE_DESCRIPTION", "Sammelt die Passwort-Datenbank, Anwesenheitsprotokoll, um eine Liste der Erweiterungen und Browser-Einstellungen.");
define("COEX_IMAGEVERIFIER_MODULE", "Bild Verifier-Modul");
define("COEX_IMAGEVERIFIER_MODULE_DESCRIPTION", "Sucht nach Bildern und überprüfen Sie sie auf mögliche Match-stego Behälter.");
define("COEX_SEARCHPROGRAM_MODULE", "Suchen Programm-Modul");
define("COEX_SEARCHPROGRAM_MODULE_DESCRIPTION", "Suchen Sie nach Spuren der installierten Programme, und in dem System gelöscht.");
define("COEX_OUTLOOK_MODULE", "Outlook-Modul");
define("COEX_OUTLOOK_MODULE_DESCRIPTION", "Er findet Korrespondenz und Kopien des Outlook Express Mail-Client.");
define("COEX_PIDGIN_MODULE", "Pidgin-Modul");
define("COEX_PIDGIN_MODULE_DESCRIPTION", "Sammelt Benutzer Korrespondenz und eine Liste seiner Kontakte, Instant Messenger-Protokolle.");
define("COEX_ICQ_MODULE", "ICQ-Modul");
define("COEX_ICQ_MODULE_DESCRIPTION", "Sammeln Sie eine Liste von Benutzer Messenger-Kontakte.");
define("COEX_SYSTEMLOG_MODULE", "Der Systemprotokoll-Modul");
define("COEX_SYSTEMLOG_MODULE_DESCRIPTION", "Es sammelt Protokolle Betriebssystem.");
define("COEX_FIREFOX_MODULE", "Firefox-Modul");
define("COEX_FIREFOX_MODULE_DESCRIPTION", "Sammelt Geschichte gleichnamigen Browser durchsuchen.");
define("COEX_ARCHIVE_MODULE", "Archiv-Modul");
define("COEX_ARCHIVE_MODULE_DESCRIPTION", "Suchen nach Dateien und zeigt Informationen über sie.");
define("ARCHITECTURE_DESCRIPTION", "Die Modularität des gesamten Systems ermöglicht es, unter den vorgeschriebenen Aufgaben schnell zu konfigurieren. Jedes Modul arbeitet unabhängig von den anderen, das Ergebnis am Ende des Systems in einem einzigen Bericht antreibt.");
define("ARCHITECTURE_SYSTEM_OF_PLUGINS", "Stecksystem");
define("ARCHITECTURE_DATA_ANALISIS", "Datenanalyse");
define("ARCHITECTURE_MODUL_N", "Modul");
define("CONTACTS", "Kontakte");
define("CONTACTS_DESCRIPTION", "Um uns zu kontaktieren, verwenden Sie bitte die Tools unten vorgeschlagen.");
define("ABOUT_US", "Über uns");
define("MADE_IN", "Hergestellt auf einem Stuhl in KIBEVS TUSUR GAP-Gruppe.");
define("DENIAL_OF_RESPONSIBILITY", "Denial-of-Verantwortung");
define("DENIAL_OF_RESPONSIBILITY_DESCRIPTION", "Die verwendeten Medien wurden aus dem Internet, die richtigen Daten-Dateien sind Eigentum ihrer rechtmäßigen Eigentümer.");
define("LICENSE_AGREEMENT", "Lizenzvereinbarung");
