<?php

define("HEADER_TITLE", "COEX-Software");
define("MENU_CAPABILITIES", "Einsatzmöglichkeiten");
define("MENU_INSTALL", "Installation");
define("MENU_ARCHITECTURE", "Architektur");
define("MENU_ABOUT", "Über uns");
define("ARCHITECTURE_OF_SYSTEM", "Systemarchitektur");
define("NEWS_OF_PROJECT", "Neues über das Projekt");
define("CAPABILITIES_INFO", "Unser Software-System sammelt Informationen aus einer Vielzahl von Quellen auf dem Zielcomputer.");
define("COEX_WHAT", "Was ist die COEX-Software?");
define("COEX_DESCRIPTION", "Die Software für Computer-Forensik im Rahmen von Gerichtsverfahren. Entwickelt um das Sammeln von Informationen über den verdächtigen Computer zu erleichtern.");
define("DOWNLOAD_AND_RUN", "Herunterladen und ausführen.");
define("CLONE_AND_BUILD", "Repository klonen und kompilieren.");
define("COEX_CHROME_MODULE", "Chrome-Modul");
define("COEX_CHROME_MODULE_DESCRIPTION", "Sammelt Informationen über die Passwort-Datenbank, das Anwesenheitsprotokoll und eine Liste der Browser-Erweiterungen und Browser-Einstellungen.");
define("COEX_IMAGEVERIFIER_MODULE", "Bild Verifier-Modul");
define("COEX_IMAGEVERIFIER_MODULE_DESCRIPTION", "Sucht nach Bildern und überprüfen Sie auf mögliche steganographische Container.");
define("COEX_SEARCHPROGRAM_MODULE", "Suchen Programm-Modul");
define("COEX_SEARCHPROGRAM_MODULE_DESCRIPTION", "Suchen Sie nach Spuren von im System gelöschter Software.");
define("COEX_OUTLOOK_MODULE", "Outlook-Modul");
define("COEX_OUTLOOK_MODULE_DESCRIPTION", "Sammelt Korrespondenz und Kopien des Outlook Express Mail-Client.");
define("COEX_PIDGIN_MODULE", "Pidgin-Modul");
define("COEX_PIDGIN_MODULE_DESCRIPTION", "Sammelt Benutzer Korrespondenz, Kontaktliste und Instant Messenger-Protokolle.");
define("COEX_ICQ_MODULE", "ICQ-Modul");
define("COEX_ICQ_MODULE_DESCRIPTION", "Sammelt die Benutzer Kontaktliste.");
define("COEX_SYSTEMLOG_MODULE", "Der Systemprotokoll-Modul");
define("COEX_SYSTEMLOG_MODULE_DESCRIPTION", "Sammelt die Betriebssystem Protokolle.");
define("COEX_FIREFOX_MODULE", "Firefox-Modul");
define("COEX_FIREFOX_MODULE_DESCRIPTION", "Sammelt den Browserverlauf.");
define("COEX_ARCHIVE_MODULE", "Archiv-Modul");
define("COEX_ARCHIVE_MODULE_DESCRIPTION", "Sucht nach Dateien und zeigt deren Informationen.");
define("COEX_SEARCH_GIT_REPO_MODULE", "SearchGitRepo-Modul");
define("COEX_SEARCH_GIT_REPO_MODULE_DESCRIPTION", "Suchen Git-Repository und zeigt Informationen über sie.");
define("COEX_SKYPE_MODULE", "Skype-Modul");
define("COEX_SKYPE_MODULE_DESCRIPTION", "Sammeln Sie eine Liste von Benutzern, Kontakten Korrespondenz, Informationen über Anrufe und Chats.");
define("COEX_THUNDERBIRD_MODULE", "Thunderbird-Modul");
define("COEX_THUNDERBIRD_MODULE_DESCRIPTION", "Findet Korrespondenz und Kopien von E-Mail-Client Thunderbird .");
define("COEX_VIBER_MODULE", "Viber-Modul");
define("COEX_VIBER_MODULE_DESCRIPTION", "Sammeln Sie eine Liste von Benutzer Messenger-Kontakte.");
define("ARCHITECTURE_DESCRIPTION", "Durch die Modularität des gesamten Systems kann die Software für die anfallenden Aufgaben schnell konfiguriert werden. Jedes Modul arbeitet unabhängig von den anderen. Das Ergebnis wird am Ende in einem einzigen Bericht zusammengefasst.");
define("ARCHITECTURE_SYSTEM_OF_PLUGINS", "Plug-in");
define("ARCHITECTURE_DATA_ANALISIS", "Datenanalyse");
define("ARCHITECTURE_MODUL_N", "Modul");
define("CONTACTS", "Kontakt");
define("CONTACTS_DESCRIPTION", "Verwenden Sie bitte die vorgeschlagenen Tools für eine Kontaktaufnahme.");
define("ABOUT_US", "Über uns");
define("MADE_IN", "Hergestellt in der Abteilung KIBEVS TUSUR der GAP-Gruppe.");
define("DENIAL_OF_RESPONSIBILITY", "Urheberrecht");
define("DENIAL_OF_RESPONSIBILITY_DESCRIPTION", "Die verwendeten Medien/Bilder stammen aus dem Internet. Sie sind Eigentum ihrer rechtmäßigen Eigentümer.");//no garanty for law-security
define("LICENSE_AGREEMENT", "Lizenzvereinbarung");
