<?php

define("HEADER_TITLE", "Computer Forensics System Coex");
define("MENU_CAPABILITIES", "Capabilities");
define("MENU_INSTALL", "Installation");
define("MENU_ARCHITECTURE", "Architecture");
define("MENU_ABOUT", "Information about us");
define("ARCHITECTURE_OF_SYSTEM", "System Architecture");
define("NEWS_OF_PROJECT", "News of project");
define("CAPABILITIES_INFO", "Our software system collects information from a variety of sources on the target machine.");
define("COEX_WHAT", "What is the COEX Software?");
define("COEX_DESCRIPTION", "The software for computer forensics within the framework of judicial proceedings, and designed to facilitate the collection of information on the suspect computer.");
define("DOWNLOAD_AND_RUN", "Download and run.");
define("CLONE_AND_BUILD", "Clone repository and compile.");
define("COEX_CHROME_MODULE", "Chrome module");
define("COEX_CHROME_MODULE_DESCRIPTION", "Collects the password database, attendance log, a list of extensions and browser settings.");
define("COEX_IMAGEVERIFIER_MODULE", "ImageVerifier module");
define("COEX_IMAGEVERIFIER_MODULE_DESCRIPTION", "Searches for images and check them for possible match-stego container.");
define("COEX_SEARCHPROGRAM_MODULE", "SearchProgram module");
define("COEX_SEARCHPROGRAM_MODULE_DESCRIPTION", "Look for traces of installed programs, and deleted in the system.");
define("COEX_OUTLOOK_MODULE", "Outlook module");
define("COEX_OUTLOOK_MODULE_DESCRIPTION", "He finds correspondence and copies of the Outlook Express mail client.");
define("COEX_PIDGIN_MODULE", "Pidgin module");
define("COEX_PIDGIN_MODULE_DESCRIPTION", "Collects user correspondence and a list of his contacts, instant messenger logs.");
define("COEX_ICQ_MODULE", "ICQ module");
define("COEX_ICQ_MODULE_DESCRIPTION", "Собирает список контактов пользователя мессенджера.");
define("COEX_SYSTEMLOG_MODULE", "SystemLog module");
define("COEX_SYSTEMLOG_MODULE_DESCRIPTION", "Gather a list of user messenger contacts.");
define("COEX_FIREFOX_MODULE", "Firefox module");
define("COEX_FIREFOX_MODULE_DESCRIPTION", "Collects browsing history eponymous browser.");
define("COEX_ARCHIVE_MODULE", "Archive module");
define("COEX_ARCHIVE_MODULE_DESCRIPTION", "Searches for files and displays information about them.");
define("COEX_SEARCH_GIT_REPO_MODULE", "SearchGitRepo module");
define("COEX_SEARCH_GIT_REPO_MODULE_DESCRIPTION", "Searches Git-repository and displays information about them.");
define("ARCHITECTURE_DESCRIPTION", "The modularity of the whole system allows you to quickly configure it under the required tasks. Each module operates independently of the others, the result of driving into a single report at the end of the system.");
define("ARCHITECTURE_SYSTEM_OF_PLUGINS", "Plug-in system");
define("ARCHITECTURE_DATA_ANALISIS", "Data analysis");
define("ARCHITECTURE_MODUL_N", "Module");
define("CONTACTS", "Contacts");
define("CONTACTS_DESCRIPTION", "To contact us, please use the tools proposed below.");
define("ABOUT_US", "About us");
define("MADE_IN", "Made in the Department KIBEVS TUSUR the GAP group.");
define("DENIAL_OF_RESPONSIBILITY", "Denial of responsibility");
define("DENIAL_OF_RESPONSIBILITY_DESCRIPTION", "Media used were taken from the Internet, the right data files belong to their rightful owners.");
define("LICENSE_AGREEMENT", "License agreement");
