<?php

define("HEADER_TITLE", "ForensicTool");
define("MENU_CAPABILITIES", "Возможности");
define("MENU_INSTALL", "Установка");
define("MENU_ARCHITECTURE", "Архитектура");
define("MENU_ABOUT", "Информация о нас");
define("ARCHITECTURE_OF_SYSTEM", "Архитектура системы");
define("NEWS_OF_PROJECT", "Новости проекта");
define("CAPABILITIES_INFO", "Наш програмный комплекс собирает информацию со множества источников на исследуемой машине.");
define("FORENSICTOOL_WHAT", "Что такое ForensicTool?");
define("FORENSICTOOL_DESCRIPTION", "Программное обеспечение для проведения компьютерной экспертизы в рамках судебного делопроизводства и призванная облегчить сбор информации об исследуемом компьютере.");
define("DOWNLOAD_AND_RUN", "Скачать и запустить.");
define("CLONE_AND_BUILD", "Клонировать репозиторий и скомпилировать.");
define("FORENSICTOOL_CHROME_MODULE", "Chrome модуль");
define("FORENSICTOOL_CHROME_MODULE_DESCRIPTION", "Собирает базу паролей, журнал посещаемости, список расширений и настройки браузера.");
define("FORENSICTOOL_IMAGEVERIFIER_MODULE", "ImageVerifier модуль");
define("FORENSICTOOL_IMAGEVERIFIER_MODULE_DESCRIPTION", "Осуществляет поиск изображений и проверяет их на возможное соответствие стего-контейнеру.");
define("FORENSICTOOL_SEARCHPROGRAM_MODULE", "SearchProgram модуль");
define("FORENSICTOOL_SEARCHPROGRAM_MODULE_DESCRIPTION", "Ищет следы установленных и удалённых программ в исследуемой системе.");
define("FORENSICTOOL_OUTLOOK_MODULE", "Outlook модуль");
define("FORENSICTOOL_OUTLOOK_MODULE_DESCRIPTION", "Находит и копирует переписку из почтового клиента Outlook Express.");
define("FORENSICTOOL_PIDGIN_MODULE", "Pidgin модуль");
define("FORENSICTOOL_PIDGIN_MODULE_DESCRIPTION", "Собирает переписку пользователя и список его контактов, журналы мессенджера.");
define("FORENSICTOOL_ICQ_MODULE", "ICQ модуль");
define("FORENSICTOOL_ICQ_MODULE_DESCRIPTION", "Собирает список контактов пользователя мессенджера.");
define("FORENSICTOOL_SYSTEMLOG_MODULE", "SystemLog модуль");
define("FORENSICTOOL_SYSTEMLOG_MODULE_DESCRIPTION", "Собирает журналы операционной системы.");
define("FORENSICTOOL_FIREFOX_MODULE", "Firefox модуль");
define("FORENSICTOOL_FIREFOX_MODULE_DESCRIPTION", "Собирает журнал посещений одноименного браузера.");
define("FORENSICTOOL_ARCHIVE_MODULE", "Archive модуль");
define("FORENSICTOOL_ARCHIVE_MODULE_DESCRIPTION", "Осуществляет поиск архивов и выводит информацию о них.");
define("FORENSICTOOL_SEARCH_GIT_REPO_MODULE", "SearchGitRepo модуль");
define("FORENSICTOOL_SEARCH_GIT_REPO_MODULE_DESCRIPTION", "Осуществляет поиск Git-репозиториев и выводит информацию о них.");
define("FORENSICTOOL_SKYPE_MODULE", "Skype модуль");
define("FORENSICTOOL_SKYPE_MODULE_DESCRIPTION", "Собирает список контактов, переписку пользователей, информацию о звонках, и чатах.");
define("FORENSICTOOL_THUNDERBIRD_MODULE", "Thunderbird модуль");
define("FORENSICTOOL_THUNDERBIRD_MODULE_DESCRIPTION", "Находит и копирует переписку из почтового клиента Thunderbird.");
define("FORENSICTOOL_VIBER_MODULE", "Viber модуль");
define("FORENSICTOOL_VIBER_MODULE_DESCRIPTION", "Собирает список контактов пользователя мессенджера.");
define("ARCHITECTURE_DESCRIPTION", "Модульность всей системы позволяет оперативно настраивать ее под необходимые задачи. Каждый модуль работает независимо от других, результат работы сводит в единый отчет по окончанию работы системы.");
define("ARCHITECTURE_SYSTEM_OF_PLUGINS", "Система плагинов");
define("ARCHITECTURE_DATA_ANALISIS", "Анализ данных");
define("ARCHITECTURE_MODUL_N", "Модуль");
define("CONTACTS", "Контакты");
define("CONTACTS_DESCRIPTION", "Для связи с нами, воспользуйтесь средствами, предложенными ниже.");
define("ABOUT_US", "О нас");
define("MADE_IN", "Сделано на кафедре КИБЭВС в ТУСУР группой ГПО.");
define("DENIAL_OF_RESPONSIBILITY", "Отказ от ответственности");
define("DENIAL_OF_RESPONSIBILITY_DESCRIPTION", "Используемые медиафайлы были взяты из сети Интернет, права данные файлы принадлежат их законным владельцам.");
define("LICENSE_AGREEMENT", "Лицензионное соглашение");

